### ISSUE TITLE
The Parkinson’s Disease EMG Dataset

### ISSUE THREAD

**Issue by GuiyinLi** [larocs/EMG-GAN#4]
Dear author:

Hello, I am reproducing the DCGANs part of this paper(Parkinson’s Disease EMG Data Augmentation and Simulation with DCGANs and Style Transfer) and code(EMG-GAN), using NinaPro DB2 data because I do not have the private dataset used in the paper.

Since my graphics card is RTX 3090 and the system is ubuntu 20.04, I was never able to run the code successfully in your environment, so I ended up having to use TensorFlow-gpu2.5 to train DCGANs and generate my signal. Still, the trained network and generated signals did not work as expected.

After that, I used the network model provided on GitHub and used the DB2 data as the reference signal, and the final generated signal was similar to the sEMG data of the Parkinson's patient used in the paper, so I don't know if the training part of the DCGANs is different from the paper due to environmental issues. Therefore, I hope I can get the data of the Parkinson's patient used in the paper, just the one used in the paper The EMG data of one patient.

Thank you for considering my request.  I'm looking forward to your response.

**Comment by zhumengtiing** [comment]
Can you give a csv format as a reference? For example, what are the rows and columns？

**Comment by rzanini** [comment]
> Dear author:
> 
> Hello, I am reproducing the DCGANs part of this paper(Parkinson’s Disease EMG Data Augmentation and Simulation with DCGANs and Style Transfer) and code(EMG-GAN), using NinaPro DB2 data because I do not have the private dataset used in the paper.
> 
> Since my graphics card is RTX 3090 and the system is ubuntu 20.04, I was never able to run the code successfully in your environment, so I ended up having to use TensorFlow-gpu2.5 to train DCGANs and generate my signal. Still, the trained network and generated signals did not work as expected.
> 
> After that, I used the network model provided on GitHub and used the DB2 data as the reference signal, and the final generated signal was similar to the sEMG data of the Parkinson's patient used in the paper, so I don't know if the training part of the DCGANs is different from the paper due to environmental issues. Therefore, I hope I can get the data of the Parkinson's patient used in the paper, just the one used in the paper The EMG data of one patient.
> 
> Thank you for considering my request. I'm looking forward to your response.

Dear contributor:
Unfortunately, due to Brazilian regulations, we cannot disclose patient's private dataset without the approval and consent that was given exclusively for this master thesis work. Therefore, we cannot share any of the data set with you. That is why we tried to provide links to NinaPro as an alternative, however, we recommend that you use your own datasets.
In order to train your DCGANs you should use it based in your dataset, so the model will learn how to generate a synthetic dataset. Since we have shared our DCGAN, you can also play with it to generate a synthetica dataset for yourself.

**Comment by GuiyinLi** [comment]
Thanks for your reply!
I used it to generate the synthetic dataset for NinaPro DB2(1KHz) and DB5(200Hz). However, the amplitude of the generated signal is small, and the DTW and FFT do not converge as the epoch increases. So may I ask if the parameters cause this in the configuration(such as num_steps or noise_dim), or if the discriminator feature network(Conv, FFT, Envelopes, and wavelet) is not applicable to DB2 and DB5?
![Reference_5000](https://user-images.githubusercontent.com/54769542/201339537-a33e03e3-617a-4c55-b7fd-4026f799ce8c.png)
![Generated_5000](https://user-images.githubusercontent.com/54769542/201339598-f8692cb4-4360-428b-bde4-720e19d69589.png)
![Losses_5000](https://user-images.githubusercontent.com/54769542/201339621-11869918-88e7-4737-95c5-5e9bab90e675.png)
![FFT_5000](https://user-images.githubusercontent.com/54769542/201339648-35926d3d-de53-442f-a07b-99043ad0054f.png)
![DTW_5000](https://user-images.githubusercontent.com/54769542/201339673-3efc97af-7b2c-4ee2-9979-9979c4373e25.png)
![Cross_correlation_5000](https://user-images.githubusercontent.com/54769542/201339682-19fe807c-5818-41e6-b949-52fecee6829f.png)

**Comment by mriganksoni** [comment]
> Dear author:
> 
> Hello, I am reproducing the DCGANs part of this paper(Parkinson’s Disease EMG Data Augmentation and Simulation with DCGANs and Style Transfer) and code(EMG-GAN), using NinaPro DB2 data because I do not have the private dataset used in the paper.
> 
> Since my graphics card is RTX 3090 and the system is ubuntu 20.04, I was never able to run the code successfully in your environment, so I ended up having to use TensorFlow-gpu2.5 to train DCGANs and generate my signal. Still, the trained network and generated signals did not work as expected.
> 
> After that, I used the network model provided on GitHub and used the DB2 data as the reference signal, and the final generated signal was similar to the sEMG data of the Parkinson's patient used in the paper, so I don't know if the training part of the DCGANs is different from the paper due to environmental issues. Therefore, I hope I can get the data of the Parkinson's patient used in the paper, just the one used in the paper The EMG data of one patient.
> 
> Thank you for considering my request. I'm looking forward to your response.

hi can you please provide me the different steps you used to prepare the data file from DB2, or can you provide me with the dataset you prepared

**Comment by GuiyinLi** [comment]
> > Dear author:
> > Hello, I am reproducing the DCGANs part of this paper(Parkinson’s Disease EMG Data Augmentation and Simulation with DCGANs and Style Transfer) and code(EMG-GAN), using NinaPro DB2 data because I do not have the private dataset used in the paper.
> > Since my graphics card is RTX 3090 and the system is ubuntu 20.04, I was never able to run the code successfully in your environment, so I ended up having to use TensorFlow-gpu2.5 to train DCGANs and generate my signal. Still, the trained network and generated signals did not work as expected.
> > After that, I used the network model provided on GitHub and used the DB2 data as the reference signal, and the final generated signal was similar to the sEMG data of the Parkinson's patient used in the paper, so I don't know if the training part of the DCGANs is different from the paper due to environmental issues. Therefore, I hope I can get the data of the Parkinson's patient used in the paper, just the one used in the paper The EMG data of one patient.
> > Thank you for considering my request. I'm looking forward to your response.
> 
> hi can you please provide me the different steps you used to prepare the data file from DB2, or can you provide me with the dataset you prepared

I‘m sorry, "It's been a long time, and I ended up using alternative methods to complete the related work.
At that time, the processing steps for this data were all based on EMG-GAN, and I simply replaced the dataset and the relevant configuration parameters (`configuration.json`), but the performance on DB5 was far from satisfactory. Both DB2 and DB5 are from [Ninapro](https://ninapro.hevs.ch/)."
This is a configuration for DB5
```json
{
  "train_split": 1.0,
  "channels": 1,
  "num_steps": 1000,
  "noise_dim": 200,
  "use_random_noise": true,
  "learning_rate": 0.0002,
  "result_folder": "",
  "training_file": "./data/S1_E1_A1_2.csv",
  "features": [
    "EMG_02"
  ],
  "rescale": true,
  "conv_activation": "relu",
  "activation_function": "tanh",
  "moving_avg_window": 100,
  "wavelet_mother": "db7",
  "wavelet_levels": 2,
  "wavelet_trainable": false,
  "use_mini_batch": true,
  "sliding_window": -1,
  "loss_function": "binary_crossentropy",
  "optimizer": "adam",
  "metrics": [
    "accuracy"
  ],
  "dropout_rate": 0.2,
  "sample_interval": 1000,
  "epochs": 5000,
  "batch_size": 100,
  "save_sample": true,
  "plot_losses": true,
  "save_models": true
}
```
